# version: '3.8' # version number is obsolete
services:
  web:
    build: apache
    container_name: web
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: html
        target: /var/www/html
        read_only: true
    depends_on:
      - sqlserver
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      # sa just works, but please create your own user
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWD}
      MSSQL_PID: Express
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_COLLATE: ${MSSQL_COLLATE}
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserverdata: